name: Build ZMK firmware

on:
  push:
    paths:
      - "build.yaml"
      - "boards/**"
      - "sofle.keymap"
      - "sofle.conf"
      - "west.yml"
      - ".github/workflows/build.yml"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
